export const mockBooks = [
  {
    id: '1',
    title: 'SSC CGL Tier I & II Comprehensive Guide',
    author: 'R.K. Gupta',
    price: 650,
    description: 'Complete guide for SSC Combined Graduate Level Examination covering all sections with previous year questions.',
    category: 'SSC',
    coverImage: 'https://images.unsplash.com/photo-1618737709778-56783e54e3f1?w=400',
    rating: 4.8,
    stock: 45,
    bestseller: true
  },
  {
    id: '2',
    title: 'Banking Awareness for SBI & IBPS Exams',
    author: 'Arihant Experts',
    price: 345,
    description: 'Detailed banking awareness material for all banking recruitment examinations including SBI PO and Clerk.',
    category: 'Banking',
    coverImage: 'https://images.unsplash.com/photo-1546800069-1f7090ae1c5c?w=400',
    rating: 4.6,
    stock: 30,
    bestseller: true
  },
  {
    id: '3',
    title: 'Indian Railways Group D Recruitment Exam',
    author: 'Dr. Lal & Jain',
    price: 425,
    description: 'Comprehensive study material for Railway Group D posts including practice sets and solved papers.',
    category: 'Railway',
    coverImage: 'https://images.unsplash.com/photo-1527404208018-43772887af59?w=400',
    rating: 4.5,
    stock: 50,
    bestseller: true
  },
  {
    id: '4',
    title: 'General Knowledge 2026',
    author: 'Manohar Pandey',
    price: 210,
    description: 'Essential general knowledge book for all competitive exams featuring current affairs and static GK.',
    category: 'Other Exams',
    coverImage: 'https://images.unsplash.com/photo-1618737709778-56783e54e3f1?w=400',
    rating: 4.7,
    stock: 100,
    bestseller: true
  },
  {
    id: '5',
    title: 'Objective General English',
    author: 'S.P. Bakshi',
    price: 480,
    description: 'A standard book for General English for all competitive exams including SSC, Banking, and Defence.',
    category: 'Other Exams',
    coverImage: 'https://images.unsplash.com/photo-1546800069-1f7090ae1c5c?w=400',
    rating: 4.9,
    stock: 60,
    bestseller: true
  },
  {
    id: '6',
    title: 'Quantitative Aptitude for Competitive Examinations',
    author: 'R.S. Aggarwal',
    price: 725,
    description: 'The bible of quantitative aptitude for all government and competitive examinations.',
    category: 'Other Exams',
    coverImage: 'https://images.unsplash.com/photo-1527404208018-43772887af59?w=400',
    rating: 5.0,
    stock: 40,
    bestseller: true
  },
  {
    id: '7',
    title: 'CTET & TETs Child Development & Pedagogy',
    author: 'Himanshi Singh',
    price: 395,
    description: 'Focused study material for Child Development and Pedagogy section of teaching eligibility tests.',
    category: 'CTET',
    coverImage: 'https://images.unsplash.com/photo-1618737709778-56783e54e3f1?w=400',
    rating: 4.8,
    stock: 25,
    bestseller: false
  },
  {
    id: '8',
    title: 'Defence: Pathfinder CDS Examination',
    author: 'Arihant Experts',
    price: 810,
    description: 'Complete guide for Combined Defence Services Examination conducted by UPSC.',
    category: 'Defence',
    coverImage: 'https://images.unsplash.com/photo-1546800069-1f7090ae1c5c?w=400',
    rating: 4.7,
    stock: 15,
    bestseller: false
  },
  {
    id: '9',
    title: 'Reasoning Ability for Banking Exams',
    author: 'Adda247 Publications',
    price: 450,
    description: 'Comprehensive reasoning book designed specifically for IBPS, SBI, and RBI exams.',
    category: 'Banking',
    coverImage: 'https://images.unsplash.com/photo-1527404208018-43772887af59?w=400',
    rating: 4.6,
    stock: 35,
    bestseller: false
  },
  {
    id: '10',
    title: 'SSC CHSL (10+2) Solved Papers',
    author: 'Kiran Prakashan',
    price: 560,
    description: 'Chapter-wise solved papers for SSC Higher Secondary Level examination.',
    category: 'SSC',
    coverImage: 'https://images.unsplash.com/photo-1618737709778-56783e54e3f1?w=400',
    rating: 4.5,
    stock: 55,
    bestseller: false
  },
  {
    id: '11',
    title: 'Railway NTPC Graduate Level Guide',
    author: 'Disha Experts',
    price: 490,
    description: 'Study package for RRB NTPC Graduate level posts covering all stages of the exam.',
    category: 'Railway',
    coverImage: 'https://images.unsplash.com/photo-1546800069-1f7090ae1c5c?w=400',
    rating: 4.4,
    stock: 20,
    bestseller: false
  },
  {
    id: '12',
    title: 'NDA/NA Entrance Exam Guide',
    author: 'R.P. Verma',
    price: 750,
    description: 'Comprehensive resource for National Defence Academy and Naval Academy entrance tests.',
    category: 'Defence',
    coverImage: 'https://images.unsplash.com/photo-1527404208018-43772887af59?w=400',
    rating: 4.7,
    stock: 28,
    bestseller: false
  }
];
